# Generated by Django 3.0.7 on 2020-06-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
