# Generated by Django 3.0.7 on 2020-06-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20200630_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_1',
            new_name='user_profile',
        ),
    ]
