# Generated by Django 3.0.7 on 2020-06-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_orderitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user_profile',
        ),
    ]
