# Generated by Django 3.0.7 on 2020-07-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_auto_20200701_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumeruserprofile',
            name='costumer_name',
        ),
    ]
