# Generated by Django 3.0.7 on 2020-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_remove_costumeruserprofile_costumer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_profile',
        ),
    ]
